services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    image: shop-backend
    container_name: backend

    volumes:
      - ./backend:/app
      - /app/node_modules

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: development
      PORT: 3000
      MONGO_URI: mongodb://mongodb:27017/shop_sphere

    depends_on:
      - mongodb

    command: npm run dev

  mongodb:
    image: mongo:8
    container_name: shop-mongodb

    ports:
      - "27017:27017"

    #command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
