services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    image: shop-backend
    container_name: backend

    env_file:
      - ./backend/.env

    volumes:
      - ./backend:/app
      - /app/node_modules

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: development
      PORT: 3000
      MONGO_URI: mongodb://mongodb:27017/shop_sphere

    depends_on:
      - mongodb

    command: npm run dev

  mongodb:
    image: mongo:8
    container_name: shop-mongodb

    ports:
      - "27017:27017"

    #command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7

    container_name: shop-sphere-redis

    restart: always

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.1

    container_name: shop-sphere-elasticsearch

    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

    ports:
      - "9200:9200"

    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

volumes:
  mongo-data:
  redis-data:
  elasticsearch-data:
